---
name: Node

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
 
      - name: "Cche dependencies"
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node_module-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/workflows/node.yml') }}

      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
       
      - name: "Install dependencies"
        if: steps.cache-node_modules.cache-hit == "false"
        run: npm ci
      
      - name: "Test"
        run: npm run test
...